# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
