# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_userspendingcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspendingcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userspendingcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpendingCategory',
        ),
        migrations.DeleteModel(
            name='UserSpendingCategory',
        ),
    ]
