# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_auto_20170705_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
