# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default=69, max_length=15),
            preserve_default=False,
        ),
    ]
