# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
