# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0010_auto_20170713_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
